apiVersion: v1
data:
  id_rsa: GITHUB_KEY
  id_rsa.pub: GITHUB_PUB_KEY
  known_hosts: KNOWN_HOSTS
kind: Secret
metadata:
  name: github-deploy-key-ancrht4u
  namespace: hyperplane-pipelines
type: Opaque

---
apiVersion: v1
data:
  id_rsa: GITHUB_KEY
  id_rsa.pub: GITHUB_PUB_KEY
  known_hosts: KNOWN_HOSTS
kind: Secret
metadata:
  name: github-deploy-key-ancrht4u
  namespace: hyperplane-core
type: Opaque

---
apiVersion: v1
data:
  id_rsa: GITHUB_KEY
  id_rsa.pub: GITHUB_PUB_KEY
  known_hosts: KNOWN_HOSTS
kind: Secret
metadata:
  name: github-deploy-key-jhub
  namespace: hyperplane-jhub
type: Opaque
---
apiVersion: v1
data:
  id_rsa: GITHUB_KEY
  id_rsa.pub: GITHUB_PUB_KEY
  known_hosts: KNOWN_HOSTS
kind: Secret
metadata:
  name: github-deploy-key-ancrht4u
  namespace: hyperplane-jhub
type: Opaque